services:
  traefik:
      image: traefik:v3.6
      labels:
        - 'traefik.http.middlewares.redirect-https.redirectscheme.scheme=https'
        - 'traefik.http.middlewares.redirect-https.redirectscheme.permanent=true'
      ports:
        - 80:80
        - 443:443
        - 8080:8080
      volumes:
        - '/var/run/docker.sock:/var/run/docker.sock:ro'
        - './docker/development/traefik.yml:/etc/traefik/dynamic/traefik.yml'
        - './docker/development/traefik-config.yml:/etc/traefik/traefik.yml'
        - './docker/development/cert.pem:/etc/certs/thetearoom.pem'
        - './docker/development/key.pem:/etc/certs/thetearoom.key.pem'
  thetearoom:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    ports:
      - 5173:5173
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.thetearoom.tls=true'
      - 'traefik.http.routers.thetearoom.rule=Host(`thetearoom.localhost`)'
      - 'traefik.http.services.thetearoom.loadbalancer.server.port=3000'
    volumes:
      - ./:/app
    env_file:
      - .env

  otel:
    image: docker.io/grafana/otel-lgtm:0.13.0
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.otel.tls=true'
      - 'traefik.http.routers.otel.rule=Host(`otel.localhost`)'
      - 'traefik.http.services.otel.loadbalancer.server.port=3000'
    volumes:
      - grafana:/data/grafana
      - prometheus:/data/prometheus
      - loki:/data/loki

volumes:
  grafana:
  prometheus:
  loki: