services:
  traefik:
      image: traefik:v3.2
      command:
        - '--log.level=DEBUG'
        - '--api.insecure=true'
        - '--providers.file.directory=/etc/traefik/dynamic'
        - '--providers.docker=true'
        - '--providers.docker.exposedbydefault=false'
        - '--entrypoints.web.address=:80'
        - '--entrypoints.websecure.address=:443'
      labels:
        - 'traefik.http.middlewares.redirect-https.redirectscheme.scheme=https'
        - 'traefik.http.middlewares.redirect-https.redirectscheme.permanent=true'
      ports:
        - 80:80
        - 443:443
        - 8080:8080
      volumes:
        - '/var/run/docker.sock:/var/run/docker.sock:ro'
        - './traefik.yml:/etc/traefik/dynamic/traefik.yml'
        - './cert.pem:/etc/certs/vaudit.pem'
        - './key.pem:/etc/certs/vaudit.key.pem'
  thetearoom:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    ports:
      - 5173:5173
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.thetearoom.tls=true'
      - 'traefik.http.routers.thetearoom.rule=Host(`thetearoom.localhost`)'
      - 'traefik.http.services.thetearoom.loadbalancer.server.port=3000'
    volumes:
      - ./:/app