name: FOSSA Dependency scan
on: push

jobs:
  dependency-scan:
    name: dependency-scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install fossa-cli from github
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash

      - name: Run FOSSA dependency scan
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: |
          fossa analyze .